name: Build and Test (iOS)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Show available simulators
        run: xcrun simctl list devices available

      - name: Select available iPhone simulator
        id: sim
        run: |
          sim=$(xcrun simctl list devices available | grep -E "iPhone.*(Booted|Shutdown)" | grep -v unavailable | head -n 1 | awk -F '[()]' '{print $1}' | xargs)
          echo "Using simulator: $sim"
          echo "simulator=$sim" >> $GITHUB_OUTPUT

      - name: Build for testing
        run: |
          xcodebuild build-for-testing \
            -project PingU.xcodeproj \
            -scheme PingU \
            -destination "platform=iOS Simulator,name=${{ steps.sim.outputs.simulator }}" \
            CODE_SIGNING_ALLOWED=NO \
            -resultBundlePath BuildResults

      - name: Run tests
        run: |
          xcodebuild test-without-building \
            -project PingU.xcodeproj \
            -scheme PingU \
            -destination "platform=iOS Simulator,name=${{ steps.sim.outputs.simulator }}" \
            CODE_SIGNING_ALLOWED=NO \
            -resultBundlePath TestResults

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: XcodeTestResults
          path: TestResults
