name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using iPhone Simulator
    runs-on: macos-14 # macos-14 supports Xcode 16.x

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Confirm Xcode version
        run: xcodebuild -version

      - name: Set scheme
        id: scheme
        run: echo "default_scheme=PingU" >> $GITHUB_OUTPUT

      - name: Get available iPhone simulator
        id: sim
        run: |
          sim_name=$(xcrun xctrace list devices 2>&1 | grep -E '^iPhone .*Simulator' | head -n 1 | sed -E 's/ *\[.*//')
          echo "Found simulator: $sim_name"
          echo "device_name=$sim_name" >> $GITHUB_OUTPUT

      - name: Build for iOS (no signing)
        run: |
          scheme=${{ steps.scheme.outputs.default_scheme }}
          if ls *.xcworkspace 1>/dev/null 2>&1; then 
            filetype_parameter="workspace"
            file_to_build=$(ls *.xcworkspace | head -n 1)
          else 
            filetype_parameter="project"
            file_to_build=$(ls *.xcodeproj | head -n 1)
          fi

          xcodebuild build-for-testing \
            -scheme "$scheme" \
            -"$filetype_parameter" "$file_to_build" \
            -destination "platform=iOS Simulator,name=${{ steps.sim.outputs.device_name }},OS=latest" \
            CODE_SIGNING_ALLOWED=NO

      - name: Run iOS Tests (no signing)
        run: |
          scheme=${{ steps.scheme.outputs.default_scheme }}
          if ls *.xcworkspace 1>/dev/null 2>&1; then 
            filetype_parameter="workspace"
            file_to_build=$(ls *.xcworkspace | head -n 1)
          else 
            filetype_parameter="project"
            file_to_build=$(ls *.xcodeproj | head -n 1)
          fi

          xcodebuild test-without-building \
            -scheme "$scheme" \
            -"$filetype_parameter" "$file_to_build" \
            -destination "platform=iOS Simulator,name=${{ steps.sim.outputs.device_name }},OS=latest" \
            CODE_SIGNING_ALLOWED=NO
