name: iOS Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-14
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: List Available Simulators (for debugging)
        run: xcrun simctl list devices available

      - name: Set Up Simulator Name
        id: simulator
        run: |
            echo "🧪 Getting available simulator..."
            SIMULATOR_INFO=$(xcrun simctl list devices available | grep -E "iPhone" | grep -v "unavailable" | head -n 1)
            echo "📦 SIMULATOR_INFO: $SIMULATOR_INFO"
            # Extract parts in parentheses
            PAREN_CONTENTS=($(echo "$SIMULATOR_INFO" | grep -oE '\([^()]+\)' | tr -d '()'))
            SIMULATOR_OS="${PAREN_CONTENTS[0]}"
            SIMULATOR_NAME=$(echo "$SIMULATOR_INFO" | sed -E 's/\s*\(.*//')
            echo "✅ SIMULATOR_NAME=$SIMULATOR_NAME"
            echo "✅ SIMULATOR_OS=$SIMULATOR_OS"
            echo "SIMULATOR_NAME=$SIMULATOR_NAME" >> $GITHUB_ENV
            echo "SIMULATOR_OS=$SIMULATOR_OS" >> $GITHUB_ENV

      - name: Build for Testing
        run: |
          xcodebuild build-for-testing \
            -project PingU.xcodeproj \
            -scheme PingU \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=$SIMULATOR_NAME,OS=17.5" \
            -resultBundlePath BuildResults

      - name: Run Tests
        run: |
          xcodebuild test-without-building \
            -project PingU.xcodeproj \
            -scheme PingU \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=$SIMULATOR_NAME,OS=17.5" \
            -resultBundlePath TestResults

      - name: Upload Test Results (optional)
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults
